In [11]:
import numpy as np
arr=np.ones((3,4))

In [6]:
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [12]:
arr*5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [19]:
np.empty((3,4))

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [25]:
np.eye(3,dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [26]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# optional

In [28]:
import pandas as pd 
pd.DataFrame(arr)

0    1    2    3
0  1.0  1.0  1.0  1.0
1  1.0  1.0  1.0  1.0
2  1.0  1.0  1.0  1.0

# exta topic


In [29]:
import random

In [34]:
random.choice((1,2,3,4,5,6))

6

In [38]:
random.choice("shahanshah")

'a'

In [39]:
random.choice("shahanshah")

's'

In [43]:
random.randrange(1,1000)

232

In [44]:
random.randrange(1,1000)

204

In [46]:
random.random()

0.6434721412373466

In [47]:
list=[1,2,3,4,5]
random.shuffle(list)

In [48]:
list

[2, 5, 3, 1, 4]

In [49]:
random.uniform(7,17)

12.56566931871968

In [51]:
np.random.rand(2,3)

array([[0.22122311, 0.69050963, 0.92329949],
       [0.18957686, 0.86268705, 0.19618845]])

In [53]:
np.random.random_sample()

0.4970381759612038

In [55]:
np.random.randint(1,4,size=(3,5))

array([[2, 1, 2, 2, 3],
       [3, 3, 2, 3, 1],
       [1, 3, 3, 3, 3]])

In [56]:
arr.shape

(3, 4)

In [57]:
arr.size

12

In [58]:
arr.ndim

2

In [59]:
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [61]:
arr.reshape(2,6)

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [62]:
arr.reshape(6,2)

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [67]:
arr.reshape(12,)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [72]:
arr.reshape(4,-4)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [74]:
arr.reshape(4,3)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [75]:
arr.reshape(4,-122)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [76]:
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [79]:
arr.size

12

In [81]:
arr.reshape(2,2,3)

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [88]:
arr3=np.zeros((1,3,4))  #3 rows ,4 colum >> 2n array  +1

In [89]:
arr3

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [91]:
type,arr3

(type,
 array([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]]))

In [93]:
arr3.ndim

3

In [94]:
arr3=np.zeros((2,3,4)) 

In [95]:
arr3

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [98]:
arr1=np.random.randint(1,10,(5,6))

In [99]:
arr1

array([[4, 5, 3, 3, 9, 9],
       [5, 4, 6, 1, 4, 8],
       [4, 9, 8, 7, 5, 9],
       [5, 3, 4, 3, 2, 5],
       [2, 3, 8, 1, 4, 9]])

In [100]:
arr1>4

array([[False,  True, False, False,  True,  True],
       [ True, False,  True, False, False,  True],
       [False,  True,  True,  True,  True,  True],
       [ True, False, False, False, False,  True],
       [False, False,  True, False, False,  True]])

In [101]:
arr1[arr1>5]

array([9, 9, 6, 8, 9, 8, 7, 9, 8, 9])

In [102]:
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [103]:
arr[0]

array([1., 1., 1., 1.])

In [104]:
arr1=np.random.randint(1,3,(3,3))
arr2=np.random.randint(1,3,(3,3))

In [105]:
arr1

array([[1, 2, 2],
       [2, 1, 1],
       [1, 1, 1]])

In [106]:
arr2

array([[2, 2, 1],
       [2, 1, 1],
       [1, 1, 2]])

In [107]:
arr1+arr2

array([[3, 4, 3],
       [4, 2, 2],
       [2, 2, 3]])

In [108]:
arr1-arr2

array([[-1,  0,  1],
       [ 0,  0,  0],
       [ 0,  0, -1]])

In [109]:
arr1*arr2

array([[2, 4, 2],
       [4, 1, 1],
       [1, 1, 2]])

# Broad casting

In [110]:
arr3=np.zeros((3,4)) 

In [111]:
arr3

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [112]:
arr3+5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [113]:
a=np.array([1,2,3,4])

In [114]:
a

array([1, 2, 3, 4])

In [116]:
arr3+a

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [118]:
arr3+a.T

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [119]:
arr.flatten()  # reduce higer higher dimensation to a d

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

# expand_dims>>expand the array by inserting a new axis 

In [122]:
arr=np.array([[1,2,3],[4,5,6]])

In [123]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [124]:
np.sum(arr)

21

In [126]:
np.(arr)

AttributeError: module 'numpy' has no attribute 'multiple'